name: Laravel

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  laravel-deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.REMOTE_USER }}
          host: ${{ secrets.REMOTE_HOST }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: 'cd /var/www/armoire-a-louer-dev && chmod u+x ./server_deploy.sh && ./server_deploy.sh'

  laravel-deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.REMOTE_USER }}
          host: ${{ secrets.REMOTE_HOST }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: 'cd /var/www/armoire-a-louer && chmod u+x ./server_deploy.sh && ./server_deploy.sh'
