name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Clear cache
      run: php artisan cache:clear
    - name: Clear config
      run: php artisan config:clear
    - name: Run migrations
      run: php artisan migrate --force
    - name: Install node dependencies
      run: npm install
    - name: Run node build
      run: npm run build
